version: "3.8"
services:

  redis:
    image: bitnami/redis:latest
    environment:
      REDIS_PASSWORD: Redis12345 
    networks:
      - redis_app
    ports:
      - "6379:6379"


networks:
  redis_app:
